package com.rgprmexcel.m4requierecoordinador;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class requiereCoordinadorOD implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String aporte;
	private java.lang.String entregaFisica;
	private java.lang.String convenio;
	private java.lang.String uaf;
	private java.lang.String fondoFijo;
	private java.lang.String tipoConvenio;
	private java.lang.String respuesta;

	public requiereCoordinadorOD() {
	}

	public java.lang.String getAporte() {
		return this.aporte;
	}

	public void setAporte(java.lang.String aporte) {
		this.aporte = aporte;
	}

	public java.lang.String getEntregaFisica() {
		return this.entregaFisica;
	}

	public void setEntregaFisica(java.lang.String entregaFisica) {
		this.entregaFisica = entregaFisica;
	}

	public java.lang.String getConvenio() {
		return this.convenio;
	}

	public void setConvenio(java.lang.String convenio) {
		this.convenio = convenio;
	}

	public java.lang.String getUaf() {
		return this.uaf;
	}

	public void setUaf(java.lang.String uaf) {
		this.uaf = uaf;
	}

	public java.lang.String getFondoFijo() {
		return this.fondoFijo;
	}

	public void setFondoFijo(java.lang.String fondoFijo) {
		this.fondoFijo = fondoFijo;
	}

	public java.lang.String getTipoConvenio() {
		return this.tipoConvenio;
	}

	public void setTipoConvenio(java.lang.String tipoConvenio) {
		this.tipoConvenio = tipoConvenio;
	}

	public java.lang.String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(java.lang.String respuesta) {
		this.respuesta = respuesta;
	}

	public requiereCoordinadorOD(java.lang.String aporte,
			java.lang.String entregaFisica, java.lang.String convenio,
			java.lang.String uaf, java.lang.String fondoFijo,
			java.lang.String tipoConvenio, java.lang.String respuesta) {
		this.aporte = aporte;
		this.entregaFisica = entregaFisica;
		this.convenio = convenio;
		this.uaf = uaf;
		this.fondoFijo = fondoFijo;
		this.tipoConvenio = tipoConvenio;
		this.respuesta = respuesta;
	}

}